#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename;

use FindBin;
use lib "$FindBin::Bin";

use DR;
use Getopt::Long::Descriptive;

my($opt, $usage) = describe_options("%c %o file-name [project-name]",
				    ["help|h" => "Show this help message"]);

print($usage->text), exit 0 if $opt->help;
die($usage->text) unless @ARGV == 1 || @ARGV == 2;

my $filename = shift;

if (! -f $filename)
{
    die "Input file $filename does not exist\n";
}

my $projname = shift;
if (!$projname)
{
    my ($name,$path,$suffix) = fileparse($filename,( 'csv','tsv' ));
    $projname = $name;
}

my $dr = DR->new();
my $ua = LWP::UserAgent->new;
my $token = $ENV{'DR_TOKEN'} or die 'no auth_token';
my $url = 'http://140.221.10.250/api/v2/projects/';

my $res = $dr->create_project($filename, $projname);
print "Created: $res\n";


