#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin";

use DR;

use strict;
use warnings;

use Getopt::Long::Descriptive;

my($opt, $usage) = describe_options("%c %o username password",
				    ["help|h" => "Show this help message"]);

print($usage->text), exit 0 if $opt->help;
die($usage->text) unless @ARGV == 1;

my $username = shift;
my $password = shift;

if (!defined $password) {
  use Term::ReadKey;
  print "Enter your password: ";
  ReadMode 'noecho';
  $password = ReadLine 0;
  chomp $password;
  ReadMode 'normal';
  print "\n";
}
my $dr = DR->new();

my $token = $dr->get_token($username, $password);

if (open(F, ">", $dr->token_path))
{
    print F "$token\n";
    close(F);
}
else
{
    die "Cannot write token file " . $dr->token_path . ": $!";
}
    
