#!/usr/bin/env perl

use strict;
use DR;
use Text::Table;

my $proj_name;
if (@ARGV)
{
    $proj_name = shift;
}

my $dr = DR->new();

my $projs = $dr->list_projects($proj_name);

my $tbl = Text::Table->new("ID", "Name", "Created", "Filename");

my @data;
my @fields;
for my $proj (@$projs)
{
    push(@data, [$proj->{id}, $proj->{projectName}, $proj->{created}, $proj->{fileName}]);
    @fields = keys %$proj;
}
# print STDERR join "\n", @fields;
$tbl->load(@data);
print $tbl;


    
