#!/usr/bin/env perl

use strict;
use Data::Dumper;
use Text::Table;
use Getopt::Long::Descriptive;

use DR;

my($opt, $usage) = describe_options("%c %o project-id",
				    ["help|h" => "Show this help message."]);

print($usage->text), exit 0 if $opt->help;
die($usage->text) unless @ARGV == 1;

my $proj_id = shift;

my $dr = DR->new();

my $models = $dr->list_models($proj_id);
    
my $tbl = Text::Table->new("ID", "Model type", "Sample %");
my @data;
for my $model (@$models)
{
    push(@data, [$model->{id}, $model->{modelType}, $model->{samplePct}]);
}
$tbl->load(@data);
print $tbl;


    
