#!/usr/bin/env perl

use strict;
use warnings;

use DR;

use Getopt::Long::Descriptive;

my($opt, $usage) = describe_options("%c %o project-id target",
				    ["await-completion|w" => "Await the completion of the model job"],
				    ["help|h" => "Show this help message"]);

print($usage->text), exit 0 if $opt->help;
die($usage->text) unless @ARGV == 2;

my $proj_id = shift;
my $target = shift;

my $dr = DR->new();

my $res = $dr->start_model_job($proj_id, $target, {}, $opt->await_completion);

